### ISSUE TITLE
Cannot detect column in database

### ISSUE THREAD

**Issue by akkaweb** [davidyell/CakePHP3-Proffer#79]
I have been testing this plugin with an application I am creating. For some time everything was working great, until a few days ago I noticed that my tests were saving good, except there was not images being uploaded and no errors at all. After debugging, I find out I am getting the following error:

 `Column not found: 1054 Unknown column 'posts.image_dir' in 'field list`

After running 

`bin/cake proffer.proffer generate posts`

`image_dir` is in fact a columns in the `posts` database table.

Since the only column not saving are the ones that Proffer needs, is there any chance there is an issue within your plugin or should I look somewhere else for the problem.

Thaks,

**Comment by M-pire** [comment]
I can confirm this issue. Was working on my own issue report, but will enter it here. After I ran "composer update" and it updated CakePHP and Proffer to latest versions, the uploads stopped working. Before, all worked ( image or normal file ). 

What I have tried:
1. Running the Proffer unittests => all succeed
2. Clean CakePHP 3-dev install + Proffer + all steps from /docs (like last time) and I can't get files to upload.
3. Get no errors in: php.ini, apache, cakephp logs, etc.

I looked at the recent commit's to CakePHP and I see they have changed some Database Type related stuff, might be related?

Thanks!

**Comment by davidyell** [comment]
I've pushed a new release this morning, so that might fix this issue. I will do some testing this morning to check.

**Comment by davidyell** [comment]
If you update to the latest release, this bug should be fixed.

https://github.com/davidyell/CakePHP3-Proffer/releases/tag/v0.2.3

Thanks for the report.

**Comment by akkaweb** [comment]
I can confirm that uploading is now working again. Thanks for your quick response. 

Just another heads up though that if I run `bin/cake bake proffer.proffer generate posts` I still see the issue. 

Not a big deal at this point, at least for me, because whatever posts I have uploaded images for, are still in DEV.

Thanks again!

**Comment by davidyell** [comment]
Okay, I'll make another ticket to tackle the bug in the shell.

**Comment by akkaweb** [comment]
Awesome.. thanks!
